"""insert storage_key and original_file_name into Media

Revision ID: 2400476bb5a0
Revises: 36b8b0093cce
Create Date: 2026-02-15 10:34:15.159309

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2400476bb5a0'
down_revision: str | Sequence[str] | None = '36b8b0093cce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('original_file_name', sa.String(length=255), nullable=False))
    op.add_column('media', sa.Column('storage_key', sa.String(length=512), nullable=False))
    op.add_column('movies', sa.Column('poster_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'poster_url')
    op.drop_column('media', 'storage_key')
    op.drop_column('media', 'original_file_name')
    # ### end Alembic commands ###
