"""nullable media title

Revision ID: 3516c91ab740
Revises: 3ceff3352080
Create Date: 2026-03-09 10:46:26.366084

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3516c91ab740"
down_revision: str | Sequence[str] | None = "3ceff3352080"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "media", "title", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "media", "title", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
