apiVersion: v1
kind: ConfigMap
metadata:
  name: video-config
data:
  DB_USER: "almas"
  DB_NAME: "video"
  DB_HOST: "db-service"
  DB_PORT: "5432"
  DB_SCHEME: "postgresql+asyncpg"
  GRPC_ADDR: "auth-service:50051"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_REGION: "us-east-1"
  S3_ENDPOINT_URL: "http://localstack-service:4566"
  S3_BUCKET_NAME: "my-test-bucket"
  S3_FORCE_PATH_STYLE: "True"
  APP_ENV: "local"
  AUTH_ADDR: "http://auth-service:8080/api/auth"
  init_video_data.sh: |
    #!/bin/sh
    
    set -e
    
    echo "Running Migrations..."
    alembic upgrade head
    
    echo "Starting Application..."
    exec "$@"
