FROM python:3.13

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
PYTHONUNBUFFERED=1

COPY requirements/dev.txt .
RUN pip install --no-cache-dir -r dev.txt

EXPOSE 8080

CMD [ "python", "src/main.py" ]
