apiVersion: v1
data:
  # Generate jwt-secret.yaml file with jwt secret files
  # ❯ kubectl create secret generic jwt-keys \            
  #   --from-file=public.pem=./secrets/jwt_public.pem \
  #   --from-file=private.pem=./secrets/jwt_private.pem \
  #   --dry-run=client -o yaml > jwt-secret.yaml
  jwt_public: and0X3B1YmxpYw==
  jwt_private: and0X3ByaXZhdGU=
kind: Secret
metadata:
  name: jwt-keys
