# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_service/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth_service/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61uth_service/auth.proto\x12\x0c\x61uth_service\"%\n\x12GetUserByIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\xa1\x01\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\x12\x14\n\x07picture\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\rdate_of_birth\x18\x06 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_pictureB\x10\n\x0e_date_of_birth2\xab\x01\n\x0b\x41uthService\x12K\n\x0bGetUserById\x12 .auth_service.GetUserByIdRequest\x1a\x1a.auth_service.UserResponse\x12O\n\rValidateToken\x12\".auth_service.ValidateTokenRequest\x1a\x1a.auth_service.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_service.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERBYIDREQUEST']._serialized_start=41
  _globals['_GETUSERBYIDREQUEST']._serialized_end=78
  _globals['_VALIDATETOKENREQUEST']._serialized_start=80
  _globals['_VALIDATETOKENREQUEST']._serialized_end=117
  _globals['_USERRESPONSE']._serialized_start=120
  _globals['_USERRESPONSE']._serialized_end=281
  _globals['_AUTHSERVICE']._serialized_start=284
  _globals['_AUTHSERVICE']._serialized_end=455
# @@protoc_insertion_point(module_scope)
