FROM python:3.13

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
PYTHONUNBUFFERED=1

COPY requirements/dev.txt .
RUN pip install --no-cache-dir -r dev.txt

EXPOSE 8081

CMD [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8081", "--reload" ]