apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-testing
data:
  NEXT_PUBLIC_API_URL: "http://wh.com/api"
  NEXT_PUBLIC_WS_URL: "ws://wh.com"
  NEXT_PUBLIC_CLOUDFRONT_URL: "https://d24lanzu8wxnoe.cloudfront.net/:path*"
  NEXT_PUBLIC_IMAGES_CLOUDFRONT_URL: "dk3at0kil7p4c.cloudfront.net"